//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@import AppKit;

@class BrowserWindowController, NSColor, NSObject, NSString, NSTrackingArea;

@interface BookmarkButton : NSButton
{
    BrowserWindowController *visibilityDelegate_;
    struct CGPoint dragMouseOffset_;
    struct CGPoint dragEndScreenLocation_;
    BOOL dragPending_;
    BOOL acceptsTrackIn_;
    NSTrackingArea *area_;
    NSColor *backgroundColor_;
}

+ (id)draggedButton;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=backgroundColor_;
@property(nonatomic) BOOL acceptsTrackIn; // @synthesize acceptsTrackIn=acceptsTrackIn_;
- (id)dragImage;
- (void)installCustomTrackingArea;
- (void)windowDidChangeActive;
- (void)windowDidChangeTheme;
- (void)viewDidMoveToWindow;
- (void)updateIconToMatchTheme;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isOpaque;
- (int)secondaryMouseUpAction:(BOOL)arg1;
- (BOOL)canBecomeKeyView;
- (void)didCloseMenu:(id)arg1 withEvent:(id)arg2;
- (void)willOpenMenu:(id)arg1 withEvent:(id)arg2;
- (void)mouseDragged:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (int)performMouseDownAction:(id)arg1;
- (void)draggingSession:(id)arg1 endedAtPoint:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
- (int)endDrag;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (void)beginDrag:(id)arg1;
- (BOOL)acceptsTrackInFrom:(id)arg1;
- (void)otherMouseUp:(id)arg1;
- (int)deltaIndicatesDragStartWithXDelta:(float)arg1 yDelta:(float)arg2 xHysteresis:(float)arg3 yHysteresis:(float)arg4 indicates:(char *)arg5;
- (void)updateTrackingAreas;
- (struct CGPoint)screenLocationForRemoveAnimation;
- (BOOL)isPulseStuckOn;
- (void)setPulseIsStuckOn:(BOOL)arg1;
- (BOOL)isEmpty;
- (BOOL)isFolder;
- (const struct BookmarkNode *)bookmarkNode;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)forceButtonBorderToStayOnAlways:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

